import type { Metadata } from 'next';
import './globals.css';
import QueryClientProviders from '@/components/common/QueryClientProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProviders>
      <html lang="en">
        <body className="relative min-h-[100dvh] w-full max-w-[480px] mx-auto">
          {children}
        </body>
      </html>
    </QueryClientProviders>
  );
}
